# Generated by Django 4.2.5 on 2023-10-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_test_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='img',
            field=models.FileField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
